# Generated by Django 5.1.2 on 2024-10-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='UsuDomain',
            fields=[
                ('id_usudomain', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9)),
                ('cargo', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('tipo_seguimiento', models.CharField(max_length=30)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
                ('id_usudomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usudomain')),
            ],
        ),
        migrations.CreateModel(
            name='Usuenti',
            fields=[
                ('id_usuenti', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9)),
                ('correo', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.entidad')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
            ],
        ),
    ]
